# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong
  tag: "3.3"

env:
  prefix: /kong_prefix/
  database: "off"

ingressController:
  enabled: true
