annotations:
  artifacthub.io/changes: |
    - "Update Ingress-Nginx version controller-v1.9.1"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: latest
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
name: open-appsec-k8s-nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.8.1
